export type MarketingStage = { label: string; color: string };
export type MarketingKpi = { value: string; label: string };

export type MarketingVertical = {
	name: string;
	emoji: string;
	sidebar: string[];
	pipeline: MarketingStage[];
	kpis: MarketingKpi[];
};

export const marketingVerticals: Record<string, MarketingVertical> = {
	contractor: {
		name: "Service Pro",
		emoji: "🏗️",
		sidebar: [
			"Dashboard",
			"Leads",
			"Jobs",
			"Communications",
			"Email History",
			"Sequences",
			"Work Orders",
			"Billing",
			"Reports",
			"Estimates",
			"Invoices",
			"Contracts",
			"Appointments",
			"Inventory",
			"Time Clock",
			"Settings",
		],
		pipeline: [
			{ label: "New Lead", color: "#3b82f6" },
			{ label: "Estimate Sent", color: "#3b82f6" },
			{ label: "Approved", color: "#f59e0b" },
			{ label: "In Progress", color: "#10b981" },
			{ label: "Complete", color: "#06d6a0" },
		],
		kpis: [
			{ value: "$24,800", label: "Pipeline Value" },
			{ value: "18", label: "Active Jobs" },
			{ value: "4.9★", label: "Review Score" },
		],
	},
	food: {
		name: "Restaurant",
		emoji: "🍰",
		sidebar: [
			"Dashboard",
			"Customers",
			"Orders",
			"Messages",
			"Email History",
			"Sequences",
			"Support",
			"Billing",
			"Reports",
			"Menu",
			"POS",
			"KDS",
			"Inventory",
			"Events",
			"Gift Cards",
			"Settings",
		],
		pipeline: [
			{ label: "New Order", color: "#3b82f6" },
			{ label: "Confirmed", color: "#3b82f6" },
			{ label: "In Prep", color: "#f59e0b" },
			{ label: "Ready", color: "#10b981" },
			{ label: "Completed", color: "#06d6a0" },
		],
		kpis: [
			{ value: "$3,420", label: "Today's Revenue" },
			{ value: "67", label: "Orders Today" },
			{ value: "12 min", label: "Avg Prep Time" },
		],
	},
	beauty: {
		name: "Beauty & Wellness",
		emoji: "💇",
		sidebar: [
			"Dashboard",
			"Clients",
			"Appointments",
			"Messages",
			"Email History",
			"Sequences",
			"Client Notes",
			"Billing",
			"Reports",
			"Appointments",
			"Memberships",
			"Gift Cards",
			"Loyalty",
			"Settings",
		],
		pipeline: [
			{ label: "Inquiry", color: "#3b82f6" },
			{ label: "Booked", color: "#3b82f6" },
			{ label: "Checked In", color: "#f59e0b" },
			{ label: "In Service", color: "#10b981" },
			{ label: "Completed", color: "#06d6a0" },
		],
		kpis: [
			{ value: "24", label: "Bookings Today" },
			{ value: "89%", label: "Retention Rate" },
			{ value: "142", label: "Active Members" },
		],
	},
	retail: {
		name: "Retail",
		emoji: "🏪",
		sidebar: [
			"Dashboard",
			"Customers",
			"Orders",
			"Messages",
			"Email History",
			"Sequences",
			"Support",
			"Billing",
			"Reports",
			"POS",
			"Inventory",
			"Barcode Scan",
			"Returns",
			"Gift Cards",
			"Loyalty",
			"Settings",
		],
		pipeline: [
			{ label: "New Order", color: "#3b82f6" },
			{ label: "Processing", color: "#3b82f6" },
			{ label: "Shipped", color: "#f59e0b" },
			{ label: "Delivered", color: "#10b981" },
			{ label: "Completed", color: "#06d6a0" },
		],
		kpis: [
			{ value: "1,247", label: "SKUs Tracked" },
			{ value: "$8,340", label: "Weekly Sales" },
			{ value: "23", label: "Low Stock Alerts" },
		],
	},
	fitness: {
		name: "Health & Fitness",
		emoji: "🏥",
		sidebar: [
			"Dashboard",
			"Members",
			"Memberships",
			"Communications",
			"Email History",
			"Sequences",
			"Support",
			"Billing",
			"Reports",
			"Events",
			"Memberships",
			"Loyalty",
			"Settings",
		],
		pipeline: [
			{ label: "Trial", color: "#3b82f6" },
			{ label: "Signed Up", color: "#3b82f6" },
			{ label: "Active", color: "#10b981" },
			{ label: "Paused", color: "#f59e0b" },
			{ label: "Cancelled", color: "#64748b" },
		],
		kpis: [
			{ value: "312", label: "Active Members" },
			{ value: "94%", label: "Renewal Rate" },
			{ value: "47", label: "Classes/Week" },
		],
	},
	realestate: {
		name: "Real Estate",
		emoji: "🏠",
		sidebar: [
			"Dashboard",
			"Leads",
			"Deals",
			"Communications",
			"Email History",
			"Sequences",
			"Requests",
			"Billing",
			"Reports",
			"Estimates",
			"Invoices",
			"Contracts",
			"Calendar",
			"Settings",
		],
		pipeline: [
			{ label: "New Lead", color: "#3b82f6" },
			{ label: "Showing", color: "#3b82f6" },
			{ label: "Offer Made", color: "#f59e0b" },
			{ label: "Under Contract", color: "#10b981" },
			{ label: "Closed", color: "#06d6a0" },
		],
		kpis: [
			{ value: "$1.2M", label: "Pipeline Value" },
			{ value: "8", label: "Active Deals" },
			{ value: "32 days", label: "Avg Close Time" },
		],
	},
	creative: {
		name: "Creative & Professional",
		emoji: "🎯",
		sidebar: [
			"Dashboard",
			"Clients",
			"Projects",
			"Email",
			"Email History",
			"Sequences",
			"Support Tickets",
			"Billing",
			"Reports",
			"Estimates",
			"Invoices",
			"Contracts",
			"Calendar",
			"Settings",
		],
		pipeline: [
			{ label: "Inquiry", color: "#3b82f6" },
			{ label: "Discovery", color: "#3b82f6" },
			{ label: "Proposal", color: "#f59e0b" },
			{ label: "Active Project", color: "#10b981" },
			{ label: "Delivered", color: "#06d6a0" },
		],
		kpis: [
			{ value: "14", label: "Active Projects" },
			{ value: "$67K", label: "Monthly Revenue" },
			{ value: "98%", label: "On-time Delivery" },
		],
	},
};

export const marketingVerticalLabels: Record<string, string> = {
	contractor: "service-pro",
	food: "restaurant",
	beauty: "beauty",
	retail: "retail",
	fitness: "health-fitness",
	realestate: "real-estate",
	creative: "creative",
};

export const marketingVerticalTabOrder = [
	"contractor",
	"food",
	"beauty",
	"retail",
	"fitness",
	"realestate",
	"creative",
] as const;

export type MarketingVerticalId = (typeof marketingVerticalTabOrder)[number];
