/**
 * Drizzle schema for the DBA "Ledger" — Cloudflare D1 edge database.
 *
 * Two tables:
 *   - leads        — inbound contact/audit requests (Turnstile-verified)
 *   - transactions — Stripe checkout completions
 *
 * Migration output lives in `packages/shared/src/db/migrations/`.
 * Run `bun run db:generate` at the monorepo root after editing this file.
 */
import {
	index,
	integer,
	sqliteTable,
	text,
	uniqueIndex,
} from "drizzle-orm/sqlite-core";

/* ── Leads ──────────────────────────────────────────────────────────────── */

export const leadSourceEnum = ["Audit_Form", "Contact_Form"] as const;
export type LeadSource = (typeof leadSourceEnum)[number];

export const leadStatusEnum = [
	"New",
	"Contacted",
	"Provisioning",
	"Closed",
] as const;
export type LeadStatus = (typeof leadStatusEnum)[number];

export const leads = sqliteTable(
	"leads",
	{
		/** UUID v4 primary key — generated by the inserting service. */
		id: text("id").primaryKey(),

		/** Primary contact email — unique across the table. */
		email: text("email").notNull(),

		/** Optional company / business name. */
		company_name: text("company_name"),

		/** Which product surface created this lead. */
		source: text("source", { enum: leadSourceEnum }).notNull(),

		/** Pipeline status. Default: 'New'. */
		status: text("status", { enum: leadStatusEnum }).notNull().default("New"),

		/**
		 * Whether Cloudflare Turnstile verification passed before this lead
		 * was written. Stored for the security-audit trail.
		 */
		turnstile_passed: integer("turnstile_passed", { mode: "boolean" })
			.notNull()
			.default(true),

		/**
		 * Arbitrary JSON string — Lighthouse scores, form messages, Stripe
		 * session id, etc. TEXT column in D1 (SQLite has no native JSON type).
		 */
		metadata: text("metadata"),

		/** Unix timestamp in milliseconds, stored as INTEGER. */
		created_at: integer("created_at", { mode: "timestamp_ms" })
			.notNull()
			.$defaultFn(() => new Date()),
	},
	(t) => [
		uniqueIndex("leads_email_unique").on(t.email),
		index("leads_status_idx").on(t.status),
		index("leads_source_idx").on(t.source),
		index("leads_created_at_idx").on(t.created_at),
	],
);

export type Lead = typeof leads.$inferSelect;
export type NewLead = typeof leads.$inferInsert;

/* ── Transactions ───────────────────────────────────────────────────────── */

export const transactionStatusEnum = ["Paid", "Failed"] as const;
export type TransactionStatus = (typeof transactionStatusEnum)[number];

export const transactions = sqliteTable(
	"transactions",
	{
		/** Stripe checkout session ID — primary key, globally unique. */
		stripe_session_id: text("stripe_session_id").primaryKey(),

		/** Email from Stripe's `customer_email` field. */
		customer_email: text("customer_email"),

		/** Amount in cents as returned by Stripe. */
		amount_total: integer("amount_total"),

		/** Product tier name from `metadata.plan_name` on the Stripe session. */
		plan_name: text("plan_name"),

		/** Payment outcome. */
		status: text("status", { enum: transactionStatusEnum })
			.notNull()
			.default("Paid"),

		/** Unix timestamp in milliseconds. */
		created_at: integer("created_at", { mode: "timestamp_ms" })
			.notNull()
			.$defaultFn(() => new Date()),
	},
	(t) => [
		index("transactions_email_idx").on(t.customer_email),
		index("transactions_created_at_idx").on(t.created_at),
	],
);

export type Transaction = typeof transactions.$inferSelect;
export type NewTransaction = typeof transactions.$inferInsert;

