/**
 * Drizzle schema for the DBA "Ledger" — Cloudflare D1 edge database.
 *
 * Migration output lives in `packages/shared/src/db/migrations/`.
 * Run `bun run db:generate` at the monorepo root to update SQL migrations
 * after touching this file.
 */
import {
	index,
	integer,
	sqliteTable,
	text,
	uniqueIndex,
} from "drizzle-orm/sqlite-core";

/** The three entry-points that produce a lead record. */
export const leadTypeEnum = ["Audit", "Contact", "Checkout"] as const;
export type LeadType = (typeof leadTypeEnum)[number];

/** Lifecycle stages in the delivery pipeline. */
export const leadStatusEnum = [
	"New",
	"Contacted",
	"Provisioning",
	"Closed",
] as const;
export type LeadStatus = (typeof leadStatusEnum)[number];

export const leads = sqliteTable(
	"leads",
	{
		/** UUID v4 primary key — generated by the inserting service. */
		id: text("id").primaryKey(),

		/** Which product surface created this lead. */
		type: text("type", { enum: leadTypeEnum }).notNull(),

		/** Primary contact email — unique across the table. */
		email: text("email").notNull(),

		/** Optional company / business name. */
		company_name: text("company_name"),

		/** Pipeline status. Default: 'New'. */
		status: text("status", { enum: leadStatusEnum }).notNull().default("New"),

		/**
		 * Whether Cloudflare Turnstile verification passed before this lead
		 * was written. Stored for security-audit purposes.
		 */
		turnstile_passed: integer("turnstile_passed", { mode: "boolean" })
			.notNull()
			.default(true),

		/**
		 * Arbitrary JSON blob — Lighthouse scores, form metadata, Stripe
		 * session id, etc. Stored as a TEXT column in D1 (SQLite).
		 */
		metadata: text("metadata", { mode: "json" }).$type<
			Record<string, unknown>
		>(),

		/** ISO-8601 timestamp (ms since epoch, stored as INTEGER in SQLite). */
		created_at: integer("created_at", { mode: "timestamp_ms" })
			.notNull()
			.$defaultFn(() => new Date()),
	},
	(t) => [
		uniqueIndex("leads_email_unique").on(t.email),
		index("leads_status_idx").on(t.status),
		index("leads_type_idx").on(t.type),
		index("leads_created_at_idx").on(t.created_at),
	],
);

export type Lead = typeof leads.$inferSelect;
export type NewLead = typeof leads.$inferInsert;
